tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "coreutils"
brew "git"
brew "htop"
brew "hub"
brew "iftop"
brew "lynx"
brew "mas"
brew "ncdu"
brew "node"
brew "speedtest-cli"
brew "thefuck"
brew "trash"
brew "wget"
brew "z"
brew "zsh"
cask "avibrazil-rdm"
cask "fork"
cask "gitkraken"
cask "iterm2"
cask "lunar"
cask "pycharm"
cask "slack"
cask "sourcetree"
cask "switchresx"
cask "tor-browser"
cask "virtualbox"
cask "zoomus"
mas "ABBYY Lingvo European", id: 467622356
mas "ColorSlurp", id: 1287239339
mas "Dark Reader for Safari", id: 1438243180
mas "DigiDoc4 Client", id: 1370791134
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
