tap "beeftornado/rmtree"
tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-eid"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "srkomodo/tap"
tap "suin/suin"
brew "bmon"
brew "coreutils"
brew "sqlite"
brew "python"
brew "htop"
brew "httpd"
brew "hub"
brew "hunspell"
brew "iftop"
brew "mas"
brew "mysql-client"
brew "ncdu"
brew "node"
brew "p7zip"
brew "php", restart_service: true
brew "shfmt"
brew "speedtest-cli"
brew "sshfs"
brew "trash"
brew "wget"
brew "zsh"
brew "srkomodo/tap/shadowfox-updater"
cask "datagrip"
cask "google-chrome"
cask "iterm2-nightly"
cask "microsoft-office"
cask "phpstorm"
cask "sip"
cask "skype"
cask "slack"
cask "visual-studio-code-insiders"
cask "xquartz"
mas "ABBYY Lingvo European", id: 467622356
mas "ColorSlurp", id: 1287239339
mas "DigiDoc4 Client", id: 1370791134
mas "MarginNote 3", id: 1423522373
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
