#!/bin/bash

# To enable globally: git config --global core.hooksPath ~/PATH/TO/FOLDER/CONTAINING/THIS/FILE

protected_branches=('master' 'main')
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [[ " ${protected_branches[*]} " =~ ${current_branch} ]]; then
  echo -en "\033[33mDANGER! You are about to push to $current_branch. To proceed, type '$current_branch' and press Enter.\033[0m\n> "
  read -r branch_input </dev/tty
  echo

  if [ "$branch_input" = "$current_branch" ]; then
    echo "Committing to $current_branch"
    exit 0 # push will execute
  fi
  echo "Not committing to $current_branch, incorrect branch name '$branch_input' entered"
  exit 1 # push will not execute
else
  exit 0 # push will execute
fi
