code --install-extension aeschli.vscode-css-formatter
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension ban.spellright
code --install-extension bierner.markdown-mermaid
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension brainfit.vscode-importmagic
code --install-extension bubersson.theme-hop-light
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cssho.vscode-svgviewer
code --install-extension ctf0.macros
code --install-extension Danny1461.css-semicolon-fix
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dzhavat.css-initial-value
code --install-extension formulahendry.auto-rename-tag
code --install-extension foxundermoon.shell-format
code --install-extension gencer.html-slim-scss-css-class-completion
code --install-extension gio00.convertplist
code --install-extension Gruntfuggly.todo-tree
code --install-extension idleberg.applescript
code --install-extension iocave.customize-ui
code --install-extension iocave.monkey-patch
code --install-extension jeff-hykin.better-shellscript-syntax
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension mattn.Lisp
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension mkaufman.HTMLHint
code --install-extension ms-python.python
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension onecrayon.theme-quietlight-vsc
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension ramyaraoa.show-offset
code --install-extension ritwickdey.LiveServer
code --install-extension sdras.night-owl
code --install-extension shinnn.stylelint
code --install-extension sleistner.vscode-fileutils
code --install-extension svipas.control-snippets
code --install-extension Tyriar.lorem-ipsum
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WallabyJs.quokka-vscode
code --install-extension wmaurer.vscode-jumpy
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
