code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension bierner.markdown-mermaid
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension brainfit.vscode-importmagic
code --install-extension Cacher.cacher-vscode
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cssho.vscode-svgviewer
code --install-extension ctf0.macros
code --install-extension Danny1461.css-semicolon-fix
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension dzhavat.css-initial-value
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-open-in-application
code --install-extension formulahendry.auto-close-tag
code --install-extension foxundermoon.shell-format
code --install-extension gencer.html-slim-scss-css-class-completion
code --install-extension gio00.convertplist
code --install-extension Gruntfuggly.todo-tree
code --install-extension icrawl.discord-vscode
code --install-extension idleberg.applescript
code --install-extension iocave.customize-ui
code --install-extension iocave.monkey-patch
code --install-extension jeff-hykin.better-shellscript-syntax
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension mattn.Lisp
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension michelemelluso.code-beautifier
code --install-extension mkaufman.HTMLHint
code --install-extension ms-python.python
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension NoHomey.theme-realgithub
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension ramyaraoa.show-offset
code --install-extension ritwickdey.LiveServer
code --install-extension sdras.night-owl
code --install-extension shinnn.stylelint
code --install-extension sleistner.vscode-fileutils
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-italian
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension svipas.control-snippets
code --install-extension Tyriar.lorem-ipsum
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WallabyJs.quokka-vscode
code --install-extension wmaurer.vscode-jumpy
code --install-extension wraith13.zoombar-vscode
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
