code --install-extension aeschli.vscode-css-formatter
code --install-extension alexcvzz.vscode-sqlite
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension ban.quietlight-plus
code --install-extension ban.spellright
code --install-extension barrsan.react-italic-theme-vscode
code --install-extension bierner.markdown-mermaid
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension brainfit.vscode-importmagic
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension ctf0.macros
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DennisVash.summer-time
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-material-theme
code --install-extension felixfbecker.php-debug
code --install-extension fisheva.eva-theme
code --install-extension formulahendry.auto-rename-tag
code --install-extension foxundermoon.shell-format
code --install-extension gio00.convertplist
code --install-extension Gruntfuggly.todo-tree
code --install-extension Hyzeta.vscode-theme-github-light
code --install-extension idleberg.applescript
code --install-extension inu1255.easy-snippet
code --install-extension James-Yu.latex-workshop
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension lehni.vscode-fix-checksums
code --install-extension lehni.vscode-titlebar-less-macos
code --install-extension liviuschera.noctis
code --install-extension mattn.Lisp
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension mkaufman.HTMLHint
code --install-extension ms-python.python
code --install-extension pepri.subtitles-editor
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension ramyaraoa.show-offset
code --install-extension ritwickdey.LiveServer
code --install-extension sdras.night-owl
code --install-extension sleistner.vscode-fileutils
code --install-extension SolarLiner.linux-themes
code --install-extension ssmi.after-dark
code --install-extension teabyii.ayu
code --install-extension Tyriar.lorem-ipsum
code --install-extension wmaurer.vscode-jumpy
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
