#!/bin/zsh

ansi() { echo -e "\e[${1}m${*:2}\e[0m"; }
underline() { ansi 4 "$@"; }

# gems, mostly for cocoapods
sudo gems update

# shell
echo -e "\n$(underline "Updating OMZ")\n"
"$ZSH"/tools/upgrade.sh

echo -e "\n$(underline Updating ZSH plugins)\n"
find -L "$HOME/.oh-my-zsh/custom" -type d -name .git | while read -r d; do
  p=$(dirname "$d")
  pn=$(basename "$p")
  pt=$(dirname "$p")
  pt=$(basename "${pt:0:((${#pt} - 1))}")
  pushd -q "${p}" || exit

  if git pull --rebase --stat; then
    printf "${BLUE}%s${NORMAL}\n" "Hooray! the $pn $pt has been updated and/or is at the current version."
  else
    printf "${RED}%s${NORMAL}\n" "There was an error updating the $pn $pt. Try again later?"
  fi

  popd &>/dev/null || exit
done

# node
echo -e "\n$(underline Updating global npm packages)\n"
npm -g update

# homebrew
echo -e "\n$(underline Updating Homebrew)\n"
brew update --verbose

echo -e "\n$(underline Updating Homebrew packages and casks)\n"
if [[ -z $(brew outdated) ]]; then
  echo "Everything up to date!"
else
  brew upgrade
fi
